# ------------------------------------------------------------------------------
# provision vm with k3s
# ------------------------------------------------------------------------------
- hosts: controlplane
  gather_facts: no
  remote_user: ubuntu
  tasks:
    - name: install k3s controlplane
      shell: |
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -

    - name: register token in variable
      become: yes
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: register token as fact
      set_fact:
        k3s_token: "{{ k3s_token.stdout }}"

- hosts: dataplane
  gather_facts: no
  remote_user: ubuntu
  tasks:
    - name: get controlplane server fqdn
      set_fact:
        k3s_url: "https://{{ groups.controlplane.0 }}:6443"
        k3s_token: "{{ hostvars[groups.controlplane.0].k3s_token }}"

    - name: install k3s controlplane
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL={{ k3s_url }} K3S_TOKEN={{ k3s_token }} sh -
