---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 9115
      targetPort: 9115
